apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-configmap-reload
data:
  config.yml: |
    debug: true
    log_file: /var/log/myapp.log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap-reload
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
        - name: kubernetes-configmap-reload
          image: mahijoe/kubernetes-configmap-reload:latest
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
          ports:
            - containerPort: 8081
      volumes:
        - name: config
          configMap:
            name: kubernetes-configmap-reload
            items:
              - key: config.yml
                path: config.yml
